#!/bin/bash -eux

export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin

export GO15VENDOREXPERIMENT=1

mkdir -p /var/vcap/store

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

go get github.com/Masterminds/glide
pushd src/github.com/Masterminds/glide
  make install
popd

cd src/github.com/pivotalservices/cfops
glide install
LOG_LEVEL=debug ginkgo integration/
