#!/bin/bash -eu

export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin

export ENV_NAME
export ENV_METADATA
export OM_SSH_KEY
export OM_USER
export OM_PASSWORD
export OM_HOSTNAME
export CF_API_URL
export OM_PROXY_INFO
export OM_VERSION

# if [ -z "$AWS_ACCESS_KEY_ID" ]; then
#   echo "Need to set AWS_ACCESS_KEY_ID"
#   exit 1
# fi
#
# if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
#   echo "Need to set AWS_SECRET_ACCESS_KEY"
#   exit 1
# fi

if [ -z "$IAAS" ]; then
  echo "Need to set IAAS"
  exit 1
fi

ENV_NAME=$(cat environment-lock/name)
ENV_METADATA=$(cat environment-lock/metadata)
OM_PROXY_INFO=$(echo "$ENV_METADATA" | jq -r .proxy)
OM_SSH_KEY=$(cat london-meta/"$IAAS"-environments/"$ENV_NAME"/"$ENV_NAME"-pcf.pem)
OM_USER=$(echo "$ENV_METADATA" | jq -r .tempest.username)
OM_PASSWORD=$(echo "$ENV_METADATA" | jq -r .tempest.password)
OM_HOSTNAME=$(echo "$ENV_METADATA" | jq -r .tempest.url | cut -d '/' -f 3)
CF_API_URL=$(echo "$ENV_METADATA" | jq -r .tempest.url | cut -d '/' -f 3 | sed 's/pcf/api/')

export GO15VENDOREXPERIMENT=1

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

go get github.com/Masterminds/glide
pushd src/github.com/Masterminds/glide
  make install
popd

cd src/github.com/pivotalservices/cfops
glide install
LOG_LEVEL=debug ginkgo -v system/
