#!/bin/bash
exitcode=0
PROD_TARGET="Production"
DEV_TARGET="Develop"
RC_TARGET="Release_Candidate"

if [ ${WERCKER_DEPLOYTARGET_NAME} == ${PROD_TARGET} ]; then
  mv ./${BUILD_DIR}/snapshot ./${BUILD_DIR}/${VERSION_TAG}

elif [ ${WERCKER_DEPLOYTARGET_NAME} == ${RC_TARGET} ]; then
  mv ./${BUILD_DIR}/snapshot ./${BUILD_DIR}/rc_${WERCKER_GIT_COMMIT}
fi

exit $exitcode
